<div class="row">
	<div class="col-sm-12">
		<div id="carousel-example-captions" class="carousel slide" data-interval="10000" data-ride="carousel">
			<ol class="carousel-indicators invisible">
				<li data-target="#carousel-example-captions" data-slide-to="0" class=""></li>
				<li class="" data-target="#carousel-example-captions" data-slide-to="1"></li>
				<li class="active" data-target="#carousel-example-captions" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item active">
					<img src="http://dev.magento.com/skin/frontend/furniturexpress/default/images/carousel/bedroom.png" alt="Bedroom Furniture">
					<div class="carousel-caption">
						<h3>Bedroom Furniture</h3>
						<p>We have huge collection of quality bedroom furniture on display. Why not come and have a look?</p>
					</div>
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-example-captions" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control" href="#carousel-example-captions" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>
</div>
<div class="row">&nbsp;</div>