<div class="row">
	<div class="col-md-12"><h3>Bedroom</h3></div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="http://www.wardrobesltd.co.uk/gallery/cretone-bedroom-furniture-3.jpg">
			<div class="category-caption">
				<h4>Bedroom</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="http://www.wardrobesltd.co.uk/gallery/verona-bedroom-furniture-1.jpg">
			<div class="category-caption">
				<h4>Sofa</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="http://www.wood-styl.cz/img/slider/slider-010.jpg">
			<div class="category-caption">
				<h4>Cupboards</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180" src="http://www.wardrobesltd.co.uk/gallery/altro-bedroom-furniture-12.jpg">
			<div class="category-caption">
				<h4>Beds</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180" src="http://www.wardrobesltd.co.uk/gallery/altro-bedroom-furniture-12.jpg">
			<div class="category-caption">
				<h4>Beds</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-2">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180" src="http://www.wardrobesltd.co.uk/gallery/altro-bedroom-furniture-12.jpg">
			<div class="category-caption">
				<h4>Beds</h4>
			</div>
		</a>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS0WxKiQegLWJ8vonNmS4uv585Dh2-07tGKpoQwt_yvakIm6iXdKA">
			<div class="category-caption">
				<h4>Samthuo</h4>
			</div>
		</a>

	</div>
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="http://www.wardrobesltd.co.uk/gallery/linea-wardrobe-range-13.jpg">
			<div class="category-caption">
				<h4>Delorrio</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180"  src="http://www.wardrobesltd.co.uk/gallery/linea-wardrobe-range-17.jpg">
			<div class="category-caption">
				<h4>Ipsum</h4>
			</div>
		</a>
	</div>
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail" href="#">
			<img alt="100%x180" data-src="holder.js/100%x180" src="http://www.wardrobesltd.co.uk/gallery/legend-bedroom-furniture-3.jpg">
			<div class="category-caption">
				<h4>Lorem</h4>
			</div>
		</a>
	</div>
</div>